### PR TITLE
Uninstall packages used only for installation, so the image is lighter by 200MB (100MB compressed)

### PR DESCRIPTION
**Pull request by knapo**

### CODE REVIEW

**Comment by knapo** [comment]
@serch Purging unzip & curl, which are not needed after installation makes the image a way lighter: 
screen shot 2017-08-29 at 09 00 56

**Comment by serch** [comment]
@knapo wow nice! we definitely don't need `unzip` but `curl` is kinda my swiss-army knife when it comes to debug any kinds of problem, we do not want it at all in our containers???

**Comment by serch** [comment]
ok guess the savings in size are more important than my love for curl, I'm merging

**Comment by knapo** [comment]
You can always install it on demand, when you actually need to debug :) But if it's needed by the app, we can keep it. 
In ruby images we usually need `libcurl4-openssl-dev` or `libcurl3-dev` for some of gems, but not entire `curl` with its all dependencies (especially ssl thingies).

**Comment by serch** [comment]
true that, I'll just install it manually when I need it

**Comment by knapo** [comment]
@serch Ok, so adding `--no-install-recommends` to `apt-get install` solves the issue too and doesn't install a shot ton of unnecessary stuff, which is only recommended. And this way curl + unzip adds only a few MBs.

**Comment by serch** [comment]
thanks, in any case I think you are correct and if I need curl I should install it when I need it

**Pull request merged**
